project:
  type: book
  output-dir: docs
#  execute: /home/sfoucher/miniconda3/bin/python
#  execute-dir: file
license: CC BY-SA
latex-auto-install: true
execute:
  cache: true
lang: fr
language:
  title-block-author-plural: "Auteurs"
  repo-action-links-issue: "Signaler un problème ou<br>formuler une suggestion"
crossref:
  fig-prefix: figure
  tbl-prefix: tableau
  sec-prefix: section
  eq-prefix: équation
  lst-prefix: bloc
  fig-title: Figure
  tbl-title: Tableau
  eq-title: Équation
  lst-title: Bloc de code
book:
  title: "Traitement d'images satellites avec Python"
  subtitle: "Première édition"
  search: true
  author: 
    - name: Samuel Foucher
      url: https://www.usherbrooke.ca/recherche/fr/specialistes/details/samuel.foucher
      affiliation: Département de géomatique appliquée<br>Université de Sherbrooke
      affiliation-url: https://www.usherbrooke.ca/geomatique/
    - name: Philippe Apparicio
      url: https://www.usherbrooke.ca/recherche/fr/specialistes/details/philippe.apparicio
      affiliation: Département de géomatique appliquée<br>Université de Sherbrooke
      affiliation-url: https://www.usherbrooke.ca/geomatique/
    - name: Yacine Bouroubi
      url: https://www.usherbrooke.ca/recherche/fr/specialistes/details/yacine-bouroubi
      affiliation: Département de géomatique appliquée<br>Université de Sherbrooke
      affiliation-url: https://www.usherbrooke.ca/geomatique/
    - name: Mickaël Germain
      url: https://www.usherbrooke.ca/recherche/fr/specialistes/details/mickael-germain
      affiliation: Département de géomatique appliquée<br>Université de Sherbrooke
      affiliation-url: https://www.usherbrooke.ca/geomatique/
    - name: Étienne Clabaut
      url: 
      affiliation: Département de géomatique appliquée<br>Université de Sherbrooke
      affiliation-url: https://www.usherbrooke.ca/geomatique/      
  date: today
  date-format: YYYY-MM-DD
  reader-mode: false
  page-footer:
    left: |
      Traitement d'images satellites avec Python.
    right: |
      Ce livre a été réalisé avec <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/couverture-full.png
  favicon: images/favicon.ico
  site-url: https://serie-python-tele.github.io/TraitementImagesPythonVol1/index.html
  repo-url: https://github.com/sfoucher/TraitementImagesPythonVol1/issues
  repo-branch: main
  issue-url: https://github.com/sfoucher/TraitementImagesPythonVol1/issues
  repo-actions:
  - issue
  downloads:
  - pdf
#  - docx
  chapters:
  - index.qmd
  - 00-auteurs.qmd
  - part: Partie 1. Importation, manipulation et visualisation de données satellitaires
  - 00-PriseEnMainPython.qmd
  - 01-ImportationManipulationImages.qmd
  - 02-RehaussementVisualisationImages.qmd
  - part: Partie 2. Transformations des données satellitaires
  - 03-TransformationSpectrales.qmd
  - 04-TransformationSpatiales.qmd
  - part: Partie 3. Classifications d'images
  - 05-ClassificationsSupervisees.qmd
#  - 06-ClassificationsNonSupervisees.qmd
#  - part: Partie 4. Données massives
#  - 07-PlateformesMegadonnees.qmd
#  - part: Partie 5. Exercices et bibliographie
#  - 08-Exercices.qmd
  - references.qmd
      
bibliography: references.bib
csl: StyleBiblio.csl

format:
  docx:
    output: "Traitement-d-images-satellites-avec-Python.docx"
  ipynb:
    code-annotations: false
    ipynb-filters:
      - my-filter.py
  html:
    colorlinks: true
    css: css/quizlib.min.css
#    html-math-method: katex
    fig-width: 8
    fig-dpi: 100
#    header-includes:
#      - \usepackage{annotate-equations}
    mermaid: 
      theme: default
    theme:
      light:
      - cosmo
      - css/r4ds.scss
    code-link: true
    fontsize: 11pt
    mainfont: Helvetica Neue,Helvetica,Arial,sans-serif
    monofont: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace









