name: atelier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - ipywidget
  - scipy
  - geemap
  - rasterio
  - rioxarray
  - scikit-image
  - pip
  - pip:
    - requests
