<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Importation et manipulation de données spatiales – Traitement d'images satellites avec Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02-RehaussementVisualisationImages.html" rel="next">
<link href="./00-PriseEnMainPython.html" rel="prev">
<link href="./images/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-05b7db12ff903b44657695d3a85c4c83.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="css/quizlib.min.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-ImportationManipulationImages.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Importation et manipulation de données spatiales</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Traitement d’images satellites avec Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/sfoucher/TraitementImagesPythonVol1/issues" title="Code source" class="quarto-navigation-tool px-1" aria-label="Code source"><i class="bi bi-github"></i></a>
    <a href="./Traitement-d-images-satellites-avec-Python.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-auteurs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">À propos des auteurs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 1. Importation, manipulation et visualisation de données satellitaires</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-PriseEnMainPython.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction au langage Python</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-ImportationManipulationImages.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Importation et manipulation de données spatiales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-RehaussementVisualisationImages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Réhaussement et visualisation d’images</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 2. Transformations des données satellitaires</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-TransformationSpectrales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transformations spectrales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-TransformationSpatiales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transformations spatiales</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Partie 3. Classifications d'images</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ClassificationsSupervisees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Classifications d’images supervisées</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#préambule" id="toc-préambule" class="nav-link active" data-scroll-target="#préambule"><span class="header-section-number">2.1</span> Préambule</a>
  <ul class="collapse">
  <li><a href="#objectifs" id="toc-objectifs" class="nav-link" data-scroll-target="#objectifs"><span class="header-section-number">2.1.1</span> Objectifs</a></li>
  <li><a href="#bibliothèques" id="toc-bibliothèques" class="nav-link" data-scroll-target="#bibliothèques"><span class="header-section-number">2.1.2</span> Bibliothèques</a></li>
  <li><a href="#données" id="toc-données" class="nav-link" data-scroll-target="#données"><span class="header-section-number">2.1.3</span> Données</a></li>
  </ul></li>
  <li><a href="#importation-dimages" id="toc-importation-dimages" class="nav-link" data-scroll-target="#importation-dimages"><span class="header-section-number">2.2</span> Importation d’images</a>
  <ul class="collapse">
  <li><a href="#formats-des-images" id="toc-formats-des-images" class="nav-link" data-scroll-target="#formats-des-images"><span class="header-section-number">2.2.1</span> Formats des images</a></li>
  <li><a href="#métadonnées-des-images" id="toc-métadonnées-des-images" class="nav-link" data-scroll-target="#métadonnées-des-images"><span class="header-section-number">2.2.2</span> Métadonnées des images</a></li>
  </ul></li>
  <li><a href="#manipulation-des-images" id="toc-manipulation-des-images" class="nav-link" data-scroll-target="#manipulation-des-images"><span class="header-section-number">2.3</span> Manipulation des images</a>
  <ul class="collapse">
  <li><a href="#manipulation-de-la-matrice-de-pixels" id="toc-manipulation-de-la-matrice-de-pixels" class="nav-link" data-scroll-target="#manipulation-de-la-matrice-de-pixels"><span class="header-section-number">2.3.1</span> Manipulation de la matrice de pixels</a></li>
  <li><a href="#information-de-base" id="toc-information-de-base" class="nav-link" data-scroll-target="#information-de-base"><span class="header-section-number">2.3.2</span> Information de base</a></li>
  <li><a href="#découpage-et-indexation-de-la-matrice" id="toc-découpage-et-indexation-de-la-matrice" class="nav-link" data-scroll-target="#découpage-et-indexation-de-la-matrice"><span class="header-section-number">2.3.3</span> Découpage et indexation de la matrice</a></li>
  <li><a href="#masquage" id="toc-masquage" class="nav-link" data-scroll-target="#masquage"><span class="header-section-number">2.3.4</span> Masquage</a></li>
  <li><a href="#calcul-dun-rapport-de-bandes" id="toc-calcul-dun-rapport-de-bandes" class="nav-link" data-scroll-target="#calcul-dun-rapport-de-bandes"><span class="header-section-number">2.3.5</span> Calcul d’un rapport de bandes</a></li>
  <li><a href="#exportation-dune-image" id="toc-exportation-dune-image" class="nav-link" data-scroll-target="#exportation-dune-image"><span class="header-section-number">2.3.6</span> Exportation d’une image</a></li>
  <li><a href="#changement-de-projection-cartographique" id="toc-changement-de-projection-cartographique" class="nav-link" data-scroll-target="#changement-de-projection-cartographique"><span class="header-section-number">2.3.7</span> Changement de projection cartographique</a></li>
  </ul></li>
  <li><a href="#données-en-géoscience" id="toc-données-en-géoscience" class="nav-link" data-scroll-target="#données-en-géoscience"><span class="header-section-number">2.4</span> Données en géoscience</a>
  <ul class="collapse">
  <li><a href="#xarray" id="toc-xarray" class="nav-link" data-scroll-target="#xarray"><span class="header-section-number">2.4.1</span> xarray</a></li>
  </ul></li>
  <li><a href="#quiz" id="toc-quiz" class="nav-link" data-scroll-target="#quiz"><span class="header-section-number">2.5</span> Quiz</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sfoucher/TraitementImagesPythonVol1/issues" class="toc-action"><i class="bi bi-github"></i>Signaler un problème ou<br>formuler une suggestion</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-chap01" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Importation et manipulation de données spatiales</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="préambule" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="préambule"><span class="header-section-number">2.1</span> Préambule</h2>
<p>Assurez-vous de lire ce préambule avant d’exécuter le reste du notebook.</p>
<section id="objectifs" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="objectifs"><span class="header-section-number">2.1.1</span> Objectifs</h3>
<p>Dans ce chapitre, nous abordons quelques formats d’images ainsi que leur lecture. Ce chapitre est aussi disponible sous la forme d’un notebook Python:</p>
<p><a href="https://colab.research.google.com/github/sfoucher/TraitementImagesPythonVol1/blob/main/notebooks/01-ImportationManipulationImages.ipynb"><img src="images/colab.png" class="img-fluid"></a></p>
<div class="bloc_objectif">
<div class="bloc_objectif-header">
<div class="bloc_objectif-icon">

</div>
<p><strong>Objectifs d’apprentissage visés dans ce chapitre</strong></p>
</div>
<p>À la fin de ce chapitre, vous devriez être en mesure de&nbsp;:</p>
<ul>
<li>connaître les principales bibliothèques Python pour lire une image;</li>
<li>accéder à l’information d’une image avant de la lire;</li>
<li>comprendre les principaux formats pour une image;</li>
<li>manipuler la matrice de la donnée d’une image avec <code>numpy</code>;</li>
<li>exploiter les métadonnées et la géoréférence avec <code>rioxarray</code> et <code>xarray</code>.</li>
</ul>
</div>
</section>
<section id="bibliothèques" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="bibliothèques"><span class="header-section-number">2.1.2</span> Bibliothèques</h3>
<p>Les bibliothèques qui vont être explorées dans ce chapitre sont les suivantes:</p>
<ul>
<li><p><a href="https://scipy.org/">SciPy</a></p></li>
<li><p><a href="https://numpy.org/">NumPy</a></p></li>
<li><p><a href="https://pypi.org/project/opencv-python/">opencv-python · PyPI</a></p></li>
<li><p><a href="https://scikit-image.org/">scikit-image</a></p></li>
<li><p><a href="https://rasterio.readthedocs.io/en/stable/">Rasterio</a></p></li>
<li><p><a href="https://docs.xarray.dev/en/stable/">Xarray</a></p></li>
<li><p><a href="https://corteva.github.io/rioxarray/stable/index.html">rioxarray</a></p></li>
</ul>
<p>Dans l’environnement Google Colab, seul <code>rioxarray</code> et <code>gdal</code> doivent être installés:</p>
<div id="9a46acd0" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>apt<span class="op">-</span>get update</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>apt<span class="op">-</span>get install gdal<span class="op">-</span><span class="bu">bin</span> libgdal<span class="op">-</span>dev</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install <span class="op">-</span>q rioxarray xrscipy</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vérifier les importations:</p>
<div id="164208e3" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rxr</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> signal</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xarray <span class="im">as</span> xr</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xrscipy</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="données" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="données"><span class="header-section-number">2.1.3</span> Données</h3>
<p>Nous utilisons ces images dans ce chapitre:</p>
<div id="2823af53" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> gdown</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>gdown.download(<span class="st">'https://drive.google.com/uc?export=download&amp;confirm=pbef&amp;id=1a6Ypg0g1Oy4AJt9XWKWfnR12NW1XhNg_'</span>, output<span class="op">=</span> <span class="st">'RGBNIR_of_S2A.tif'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>gdown.download(<span class="st">'https://drive.google.com/uc?export=download&amp;confirm=pbef&amp;id=1a4PQ68Ru8zBphbQ22j0sgJ4D2quw-Wo6'</span>, output<span class="op">=</span> <span class="st">'landsat7.tif'</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>gdown.download(<span class="st">'https://drive.google.com/uc?export=download&amp;confirm=pbef&amp;id=1_zwCLN-x7XJcNHJCH6Z8upEdUXtVtvs1'</span>, output<span class="op">=</span> <span class="st">'berkeley.jpg'</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wget https:<span class="op">//</span>raw.githubusercontent.com<span class="op">/</span>sfoucher<span class="op">/</span>TraitementImagesPythonVol1<span class="op">/</span>refs<span class="op">/</span>heads<span class="op">/</span>main<span class="op">/</span>images<span class="op">/</span>modis<span class="op">-</span>aqua.PNG <span class="op">-</span>O modis<span class="op">-</span>aqua.PNG</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vérifiez que vous êtes capable de les lire:</p>
<div id="b6367529" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> rxr.open_rasterio(<span class="st">'berkeley.jpg'</span>, mask_and_scale<span class="op">=</span> <span class="va">True</span>) <span class="im">as</span> img_rgb:</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(img_rgb)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> rxr.open_rasterio(<span class="st">'RGBNIR_of_S2A.tif'</span>, mask_and_scale<span class="op">=</span> <span class="va">True</span>) <span class="im">as</span> img_rgbnir:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(img_rgbnir)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="importation-dimages" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="importation-dimages"><span class="header-section-number">2.2</span> Importation d’images</h2>
<p>La première étape avant tout traitement est d’accéder à la donnée image pour qu’elle soit manipulée par le langage Python. L’imagerie satellite présente certains défis notamment en raison de la taille parfois très importante des images. Il existe maintenant certaines bibliothèques, comme <a href="https://docs.xarray.dev/en/stable/">Xarray</a>, qui visent à optimiser la lecture et l’écriture de grandes images. Il est donc conseillé de toujours garder un oeil sur l’espace mémoire occupé par les variables Python représentant les images. La librairie principale en géomatique qui permettre d’importer (et d’exporter) de l’imagerie est la librairie <a href="https://gdal.org">GDAL</a> qui rassemble la plupart des formats sous forme de <em>driver</em> (ou pilote en français).</p>
<p>Dans le domaine de la géomatique, il faut prêter attention à quatre caractéristiques principales des images:</p>
<p>1. <strong>La matrice des données</strong> elle-même qui contient les valeurs brutes des pixels. Cette matrice sera souvent un cube à trois dimensions. En Python, ce cube sera le plus souvent un objet de la librairie <a href="https://numpy.org/">NumPy</a> (voir la section « Manipulation de la matrice de pixels » plus bas).</p>
<p>2. <strong>La dynamique des images</strong> c.-à.-d le format de stockage des valeurs individuelles (octet, entier, double, etc.). Ce format décide principalement de la résolution radiométrique et des valeurs minimales et maximales supportées.</p>
<p>3. <strong>Le nombre de bandes</strong> spectrales de l’image qui est souvent supérieur à trois et peut atteindre plusieurs centaines de bandes pour certains capteurs (notamment hyperspectraux).</p>
<p>4. <strong>La métadonnée</strong> qui va transporter l’information auxiliaire de l’image comme les dimensions et la position de l’image, la date, etc. Cette donnée auxiliaire prendra souvent la forme d’un dictionnaire Python. Elle contiendra aussi l’information de géoréférence.</p>
<p>Les différents formats se distinguent principalement sur la manière dont ces quatre caractéristiques sont gérées.</p>
<section id="formats-des-images" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="formats-des-images"><span class="header-section-number">2.2.1</span> Formats des images</h3>
<p>Il existe de nombreux formats numériques pour la donnée de type image parfois appelé donnée matricielle ou donnée <em>raster</em>. La librairie GDAL rassemble la plupart des formats matriciels rencontrés en géomatique (voir <a href="https://gdal.org/en/latest/drivers/raster/index.html">Raster drivers — GDAL documentation</a> pour une liste complète).</p>
<p>On peut distinguer deux grandes familles de format:</p>
<p>1. Les formats de type <strong>RVB</strong> issus de l’imagerie numérique grand public comme <a href="https://gdal.org/en/latest/drivers/raster/jpeg.html#raster-jpeg">JPEG</a>, <a href="https://gdal.org/en/latest/drivers/raster/png.html#raster-png">png</a>, etc. Ces formats ne supportent généralement que trois bandes au maximum (rouge, vert et bleu) et des valeurs de niveaux de gris entre 0 et 255 (format dit 8 bits ou <code>uint8</code>).</p>
<p>2. <strong>Les géo-formats</strong> issus des domaines scientifiques ou techniques comme GeoTIFF, HDF5, NetCDF, etc. qui peuvent inclure plus que trois bandes et des dynamiques plus élevées (16 bits ou même float).</p>
<p>Les formats RVB restent très utilisés en Python notamment par les bibliothèques dites de vision par ordinateur (<em>Computer Vision</em>) comme OpenCV et scikit-image ainsi que les grandes bibliothèques en apprentissage profond (PyTorch, Tensorflow).</p>
<div class="bloc_package">
<div class="bloc_package-header">
<div class="bloc_package-icon">

</div>
<p><strong>Installation de gdal dans un système Linux</strong></p>
</div>
<div class="bloc_package-body">
<ul>
<li>Pour installer GDAL&nbsp;:</li>
</ul>
<pre><code>!apt-get update
!apt-get install gdal-bin libgdal-dev</code></pre>
</div>
</div>
<section id="formats-de-type-rvb" class="level4" data-number="2.2.1.1">
<h4 data-number="2.2.1.1" class="anchored" data-anchor-id="formats-de-type-rvb"><span class="header-section-number">2.2.1.1</span> Formats de type RVB</h4>
<p>Les premiers formats pour de l’imagerie à une bande (monochrome) et à trois bandes (image couleur rouge-vert-bleu) sont issus du domaine des sciences de l’ordinateur. On trouvera, entre autres, les formats pbm, png et jpeg. Ces formats supportent peu de métadonnées et sont placées dans un entête (<em>header</em>) très limité. Cependant, ils restent très populaires dans le domaine de la vision par ordinateur et sont très utilisés en apprentissage profond en particulier. Pour la lecture des images RVB, on peut utiliser les bibliothèques Rasterio, <a href="https://he-arc.github.io/livre-python/pillow/index.html">PIL</a> ou <a href="https://docs.opencv.org/4.10.0/index.html">OpenCV</a>.</p>
<section id="lecture-avec-la-librairie-pil" class="level5" data-number="2.2.1.1.1">
<h5 data-number="2.2.1.1.1" class="anchored" data-anchor-id="lecture-avec-la-librairie-pil"><span class="header-section-number">2.2.1.1.1</span> Lecture avec la librairie PIL</h5>
<p>La librairie PIL retourne un objet de type <code>PngImageFile</code>, l’affichage de l’image se fait directement dans la cellule de sortie.</p>
<div id="3ba0f1a8" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> PIL <span class="im">import</span> Image</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> Image.<span class="bu">open</span>(<span class="st">'modis-aqua.PNG'</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>img</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>
<figure class="figure">
<p><img src="01-ImportationManipulationImages_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lecture-avec-la-librairie-opencv" class="level5" data-number="2.2.1.1.2">
<h5 data-number="2.2.1.1.2" class="anchored" data-anchor-id="lecture-avec-la-librairie-opencv"><span class="header-section-number">2.2.1.1.2</span> Lecture avec la librairie OpenCV</h5>
<p>La librairie <a href="https://docs.opencv.org/4.10.0/index.html">OpenCV</a> est aussi très populaire en vision par ordinateur. La fonction <code>imread</code> donne directement un objet de type NumPy en sortie.</p>
<div id="7a538f10" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cv2</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> cv2.imread(<span class="st">'modis-aqua.PNG'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>img</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>array([[[17, 50, 33],
        [15, 49, 31],
        [14, 48, 30],
        ...,
        [23, 56, 36],
        [23, 55, 36],
        [22, 55, 36]],

       [[18, 51, 34],
        [16, 50, 32],
        [15, 49, 32],
        ...,
        [27, 59, 40],
        [28, 60, 41],
        [27, 60, 41]],

       [[18, 53, 35],
        [18, 52, 34],
        [18, 51, 34],
        ...,
        [31, 64, 44],
        [34, 66, 47],
        [33, 65, 46]],

       ...,

       [[34, 74, 48],
        [35, 73, 48],
        [34, 70, 46],
        ...,
        [41, 74, 54],
        [41, 73, 54],
        [41, 73, 54]],

       [[36, 76, 50],
        [36, 74, 49],
        [35, 71, 47],
        ...,
        [37, 70, 51],
        [38, 71, 51],
        [38, 71, 51]],

       [[36, 76, 50],
        [35, 73, 48],
        [33, 69, 45],
        ...,
        [31, 63, 44],
        [33, 65, 46],
        [33, 66, 46]]], shape=(442, 553, 3), dtype=uint8)</code></pre>
</div>
</div>
<p>Attention : la fonction <code>imread</code> d’OpenCV renvoie les canaux dans l’ordre <strong>BGR</strong> (bleu, vert, rouge) et non RGB. Il faut convertir l’image avant de l’afficher correctement avec <code>matplotlib</code> :</p>
<div id="3bff638b" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>img_bgr <span class="op">=</span> cv2.imread(<span class="st">'modis-aqua.PNG'</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>img_rgb <span class="op">=</span> cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)   <span class="co"># BGR -&gt; RGB</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].imshow(img_bgr)<span class="op">;</span> ax[<span class="dv">0</span>].set_title(<span class="st">"Sans conversion (BGR)"</span>)<span class="op">;</span> ax[<span class="dv">0</span>].axis(<span class="st">'off'</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].imshow(img_rgb)<span class="op">;</span> ax[<span class="dv">1</span>].set_title(<span class="st">"Après conversion (RGB)"</span>)<span class="op">;</span> ax[<span class="dv">1</span>].axis(<span class="st">'off'</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="01-ImportationManipulationImages_files/figure-html/cell-8-output-1.png" width="640" height="267" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lecture-avec-la-librairie-rasterio" class="level5" data-number="2.2.1.1.3">
<h5 data-number="2.2.1.1.3" class="anchored" data-anchor-id="lecture-avec-la-librairie-rasterio"><span class="header-section-number">2.2.1.1.3</span> Lecture avec la librairie RasterIO</h5>
<p>Rien ne nous empêche de lire une image de format RVB avec <a href="https://rasterio.readthedocs.io/en/stable/">RasterIO</a> comme décrit dans ci-dessous. Vous noterez cependant les avertissements concernant l’absence de géoréférence pour ce type d’image.</p>
<div id="0f6e9422" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>img<span class="op">=</span> rasterio.<span class="bu">open</span>(<span class="st">'modis-aqua.PNG'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>img</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>&lt;open DatasetReader name='modis-aqua.PNG' mode='r'&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="le-format-geotiff" class="level4" data-number="2.2.1.2">
<h4 data-number="2.2.1.2" class="anchored" data-anchor-id="le-format-geotiff"><span class="header-section-number">2.2.1.2</span> Le format GeoTiff</h4>
<p>Le format GeoTIFF est une extension du format TIFF (Tagged Image File Format) qui permet d’incorporer des métadonnées géospatiales directement dans un fichier image. Développé initialement par Dr.&nbsp;Niles Ritter au Jet Propulsion Laboratory de la <a href="https://www.earthdata.nasa.gov/esdis/esco/standards-and-practices/geotiff" target="_blank">NASA</a> dans les années 1990, GeoTIFF est devenu un standard de facto pour le stockage et l’échange d’images géoréférencées dans les domaines de la télédétection et des systèmes d’information géographique (SIG). Ce format supporte plus que trois bandes aussi longtemps que ces bandes sont de même dimension.</p>
<p>Le format GeoTIFF est très utilisé et est largement supporté par les bibliothèques et logiciels géospatiaux, notamment <a href="https://gdal.org">GDAL</a> (<em>Geospatial Data Abstraction Library</em>), qui offre des capacités de lecture et d’écriture pour ce format. Cette compatibilité étendue a contribué à son adoption généralisée dans la communauté géospatiale.</p>
<section id="standardisation-par-logc" class="level5" data-number="2.2.1.2.1">
<h5 data-number="2.2.1.2.1" class="anchored" data-anchor-id="standardisation-par-logc"><span class="header-section-number">2.2.1.2.1</span> Standardisation par l’OGC</h5>
<p>Le standard GeoTIFF proposé par l’Open Geospatial Consortium (OGC) en 2019 formalise et étend les spécifications originales du format GeoTIFF, offrant une norme robuste pour l’échange d’images géoréférencées. Cette standardisation, connue sous le nom d’OGC GeoTIFF 1.1 <span class="citation" data-cites="OGCGeoTIFF">(<a href="references.html#ref-OGCGeoTIFF" role="doc-biblioref">2019</a>)</span>, apporte plusieurs améliorations et clarifications importantes.</p>
</section>
</section>
<section id="le-format-cog" class="level4" data-number="2.2.1.3">
<h4 data-number="2.2.1.3" class="anchored" data-anchor-id="le-format-cog"><span class="header-section-number">2.2.1.3</span> Le format COG</h4>
<p>Une innovation récente dans l’écosystème GeoTIFF est le format <em>Cloud Optimized GeoTIFF</em> (<a href="http://cogeo.org/">COG</a>), conçu pour faciliter l’utilisation de fichiers GeoTIFF hébergés sur des serveurs web HTTP. Le COG permet aux utilisateurs et aux logiciels d’accéder à des parties spécifiques du fichier sans avoir à le télécharger entièrement, ce qui est particulièrement utile pour les applications basées sur l’infonuagique.</p>
</section>
</section>
<section id="métadonnées-des-images" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="métadonnées-des-images"><span class="header-section-number">2.2.2</span> Métadonnées des images</h3>
<p>La manière la plus directe d’accéder à la métadonnée d’une image est d’utiliser les commandes <a href="https://rasterio.readthedocs.io/en/stable/cli.html#info"><code>rio info</code></a> de la librairie Rasterio ou <code>gdalinfo</code> de la librairie <code>gdal</code>. Le résultat est imprimé dans la sortie standard ou sous forme d’un dictionnaire Python.</p>
<div id="d47954ee" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>gdalinfo RGBNIR_of_S2A.tif</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>/usr/bin/sh: 1: gdalinfo: not found</code></pre>
</div>
</div>
<p>Le plus simple est d’utiliser la fonction <code>rio info</code>:</p>
<div id="f706ee16" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>rio info RGBNIR_of_S2A.tif <span class="op">--</span>indent <span class="dv">2</span> <span class="op">--</span>verbose</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Depuis Python, <code>rasterio</code> donne accès à ces mêmes informations sous forme d’attributs et d’un dictionnaire de métadonnées :</p>
<div id="12d464ac" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rasterio</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> rasterio.<span class="bu">open</span>(<span class="st">'RGBNIR_of_S2A.tif'</span>) <span class="im">as</span> src:</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Nombre de bandes :"</span>, src.count)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Dimensions (lignes, colonnes) :"</span>, src.height, src.width)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Type des pixels :"</span>, src.dtypes[<span class="dv">0</span>])</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Système de coordonnées :"</span>, src.crs)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Résolution (m) :"</span>, src.res)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Emprise :"</span>, src.bounds)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    meta <span class="op">=</span> src.meta            <span class="co"># toutes les métadonnées dans un dictionnaire</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>meta</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de bandes : 4
Dimensions (lignes, colonnes) : 1926 2074
Type des pixels : uint16
Système de coordonnées : EPSG:32618
Résolution (m) : (10.0, 10.0)
Emprise : BoundingBox(left=731780.0, bottom=5021540.0, right=752520.0, top=5040800.0)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': None,
 'width': 2074,
 'height': 1926,
 'count': 4,
 'crs': CRS.from_wkt('PROJCS["WGS 84 / UTM zone 18N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-75],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32618"]]'),
 'transform': Affine(10.0, 0.0, 731780.0,
        0.0, -10.0, 5040800.0)}</code></pre>
</div>
</div>
</section>
</section>
<section id="manipulation-des-images" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="manipulation-des-images"><span class="header-section-number">2.3</span> Manipulation des images</h2>
<section id="manipulation-de-la-matrice-de-pixels" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="manipulation-de-la-matrice-de-pixels"><span class="header-section-number">2.3.1</span> Manipulation de la matrice de pixels</h3>
<p>La donnée brute de l’image est généralement contenue dans un cube matricielle à trois dimensions (deux dimensions spatiales et une dimension spectrale). Comme exposé précédemment, la librairie dite <em>“fondationnelle”</em> pour la manipulation de matrices en Python est <a href="https://numpy.org/">NumPy</a>. Cette librairie contient un nombre très important de fonctionnalités couvrant l’algèbre linéaire, les statistiques, etc.; elle constitue la fondation de nombreuses bibliothèques en traitement numérique (voir (<a href="#fig-naturenumpy1" class="quarto-xref">figure&nbsp;<span>2.1</span></a>))</p>
<div id="fig-naturenumpy1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-naturenumpy1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/41586_2020_2649_Fig2_HTML.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-naturenumpy1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: La librairie NumPy est le fondement de nombreuses bibliothèques scientifiques (d’après <span class="citation" data-cites="NumpyNature">(<a href="references.html#ref-NumpyNature" role="doc-biblioref">Harris 2020</a>)</span>).
</figcaption>
</figure>
</div>
</section>
<section id="information-de-base" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="information-de-base"><span class="header-section-number">2.3.2</span> Information de base</h3>
<p>Les deux informations de base à afficher sur une matrice sont 1) les dimensions de la matrice et 2) le format de stockage (le type). Pour cela, on peut utiliser le code ci-dessous, dont le résultat nous informe que la matrice a trois dimensions et une taille de <code>(442, 553, 3)</code> et un type <code>uint8</code> qui représente 1 octet (8 bit). Par conséquent, la matrice a <code>442</code> lignes, <code>553</code> colonnes et <code>3</code> canaux ou bandes. Il faut prêter une attention particulière aux valeurs minimales et maximales tolérées par le type de la donnée comme indiqué dans le (<a href="#tbl-numpytype" class="quarto-xref">tableau&nbsp;<span>2.1</span></a>) (voir aussi <a href="https://numpy.org/doc/stable/user/basics.types.html">Data types — NumPy v2.1 Manual</a>).</p>
<div id="cfc2e7f9" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cv2</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> cv2.imread(<span class="st">'modis-aqua.PNG'</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Nombre de dimensions: '</span>,img.ndim)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Dimensions de la matrice: '</span>,img.shape)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Type de la donnée: '</span>,img.dtype)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de dimensions:  3
Dimensions de la matrice:  (442, 553, 3)
Type de la donnée:  uint8</code></pre>
</div>
</div>
<div class="cell" data-execution_count="14">
<div id="tbl-numpytype" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="14">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-numpytype-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tableau&nbsp;2.1: Type de données de NumPy
</figcaption>
<div aria-describedby="tbl-numpytype-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 23%">
<col style="width: 25%">
<col style="width: 19%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">dtype</th>
<th style="text-align: left;">Nom</th>
<th style="text-align: right;">Taille (bits)</th>
<th style="text-align: left;">Min</th>
<th style="text-align: left;">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">uint8</td>
<td style="text-align: left;">unsigned char</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">255</td>
</tr>
<tr class="even">
<td style="text-align: left;">int8</td>
<td style="text-align: left;">signed char</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">-128</td>
<td style="text-align: left;">127</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uint16</td>
<td style="text-align: left;">unsigned short</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">65535</td>
</tr>
<tr class="even">
<td style="text-align: left;">int16</td>
<td style="text-align: left;">short</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">-32768</td>
<td style="text-align: left;">32767</td>
</tr>
<tr class="odd">
<td style="text-align: left;">uint32</td>
<td style="text-align: left;">unsigned int</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">4294967295</td>
</tr>
<tr class="even">
<td style="text-align: left;">int32</td>
<td style="text-align: left;">int</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">-2147483648</td>
<td style="text-align: left;">2147483647</td>
</tr>
<tr class="odd">
<td style="text-align: left;">float32</td>
<td style="text-align: left;">float</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">-3.4e38</td>
<td style="text-align: left;">3.4e38</td>
</tr>
<tr class="even">
<td style="text-align: left;">float64</td>
<td style="text-align: left;">double</td>
<td style="text-align: right;">64</td>
<td style="text-align: left;">-1.8e308</td>
<td style="text-align: left;">1.8e308</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="découpage-et-indexation-de-la-matrice" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="découpage-et-indexation-de-la-matrice"><span class="header-section-number">2.3.3</span> Découpage et indexation de la matrice</h3>
<p>L’indexation et le découpage (<em>slicing</em>) des matrices dans NumPy sont des techniques essentielles pour manipuler efficacement les données multidimensionnelles en Python, offrant une syntaxe puissante et flexible pour accéder et modifier des sous-ensembles spécifiques d’éléments dans les tableaux (voir <a href="#fig-naturenumpy2" class="quarto-xref">figure&nbsp;<span>2.2</span></a>). Indexer une matrice consiste à accéder à une valeur dans la matrice pour une position particulière, la syntaxe générale est <code>matrice[ligne, colonne, bande]</code> et est similaire à la manipulation des <a href="https://docs.python.org/fr/3/tutorial/introduction.html#lists">listes</a> en Python. Les indices commencent à <code>0</code> et se termine à la <code>taille-1</code> de l’axe considéré.</p>
<div id="fig-naturenumpy2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-naturenumpy2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/41586_2020_2649_Fig1_HTML.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-naturenumpy2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Vue d’ensemble des opérations de base des matrices avec NumPy
</figcaption>
</figure>
</div>
<p>Le découpage (ou <em>slicing</em> en anglais) consiste à produire une nouvelle matrice qui est un sous-ensemble de la matrice d’origine. Un découpage se fait avec le symbole ‘:’, la syntaxe générale pour définir un découpage est <code>[début:fin:pas]</code>. Si on ne spécifie pas <code>début</code> ou <code>fin</code> alors les valeurs 0 ou <code>dimension-1</code> sont considérées implicitement. Quelques exemples :</p>
<ul>
<li>choisir un pixel en particulier avec toutes les bandes : <code>matrice[1, 1, :]</code>;</li>
<li>choisir la troisième colonne (indice 2) avec toutes les bandes : <code>matrice[:, 2, :]</code>.</li>
</ul>
<p>La syntaxe de base pour le découpage (<em>slicing</em>) des tableaux NumPy repose sur l’utilisation des deux-points (<code>:</code>) à l’intérieur des crochets d’indexation. Cette notation permet de sélectionner des plages d’éléments de manière concise et intuitive. La structure générale du découpage est <code>matrice[start:stop:step]</code>, où : 1. <code>start</code> représente l’index de départ (inclus) 2. <code>stop</code> indique l’index de fin (exclu) 3. <code>step</code> définit l’intervalle entre chaque élément sélectionné</p>
<p>Si l’un de ces paramètres est omis, NumPy utilise des valeurs par défaut : 0 pour <code>start</code>, la taille du tableau pour <code>stop</code>, et 1 pour <code>step</code>. Par exemple, pour un tableau unidimensionnel <code>array</code>, on peut extraire les éléments du deuxième au quatrième avec <code>array[1:4]</code>. Pour sélectionner tous les éléments à partir du troisième, on utiliserait <code>array[2:]</code>. Cette syntaxe s’applique également aux tableaux multidimensionnels, où chaque dimension est séparée par une virgule. Ainsi, pour une matrice 2D m, <code>m[0:2, 1:3]</code> sélectionnerait une sous-matrice 2x2 composée des deux premières lignes et des deuxième et troisième colonnes. L’indexation négative est également supportée, permettant de compter à partir de la fin du tableau. Par exemple, <code>a[-3:]</code> sélectionnerait les trois derniers éléments d’un tableau.</p>
<div id="52ed1afc" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cv2</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> cv2.imread(<span class="st">'modis-aqua.PNG'</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>img_col <span class="op">=</span> img[:,<span class="dv">1</span>,:]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Nombre de dimensions: '</span>,img_col.ndim)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Dimensions de la matrice: '</span>,img_col.shape)</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nombre de dimensions:  2
Dimensions de la matrice:  (442, 3)</code></pre>
</div>
</div>
<div class="bloc_aller_loin">
<div class="bloc_aller_loin-header">
<div class="bloc_aller_loin-icon">

</div>
<p><strong>Une vue versus une copie</strong></p>
</div>
<div class="bloc_aller_loin-body">
<p>Avec NumPy, les manipulations peuvent créer des vues ou des copies. Une vue est une simple représentation de la même donnée originale alors qu’une copie est un nouvel espace mémoire.</p>
<p>Par défaut, un découpage créé une vue.</p>
<p>On peut vérifier si l’espace mémoire est partagé avec <code>np.shares_memory(arr, slice_arr)</code>.</p>
<p>On peut toujours forcer une copie avec la méthode <code>copy()</code></p>
</div>
</div>
<!--
#### Exemple 1: calcul d'un rapport de bande

#### Exemple 2: application d'un filtrage spatial

### Mosaïquage, masquage et découpage 
-->
</section>
<section id="masquage" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4" class="anchored" data-anchor-id="masquage"><span class="header-section-number">2.3.4</span> Masquage</h3>
<p>L’utilisation d’un masque est un outil important en traitement d’image car la plupart des images de télédétection contiennent des pixels non valides qu’il faut exclure des traitements (ce que l’on appelle le <em>no data</em> en Anglais). Il y a plusieurs raison possibles pour la présence de pixels non valides:</p>
<ol type="1">
<li><p>L’image est projetée dans une grille cartographique et certaines zones, généralement situées en dehors de l’empreinte au sol du capteur, sont à exclure.</p></li>
<li><p>La présence de nuages que l’on veut exclure.</p></li>
<li><p>La présence de pixels erronés dus à des problèmes de capteurs.</p></li>
<li><p>La présence de valeurs non numériques (<em>not a number</em> ou <code>nan</code>)</p></li>
</ol>
<p>La librairie NumPy fournit des mécanismes pour exclure automatiquement certaines valeurs. Le module <code>numpy.ma</code> permet de créer un tableau masqué où les pixels non valides sont ignorés par les calculs statistiques :</p>
<div id="292629d9" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Une petite image dont la valeur 0 représente le "no data"</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> np.array([[<span class="dv">12</span>,  <span class="dv">0</span>, <span class="dv">15</span>],</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                [ <span class="dv">8</span>, <span class="dv">20</span>,  <span class="dv">0</span>],</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                [ <span class="dv">0</span>, <span class="dv">21</span>, <span class="dv">23</span>]], dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Masquer les pixels égaux à 0 : ils seront ignorés par les statistiques</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>img_masque <span class="op">=</span> np.ma.masked_equal(img, <span class="dv">0</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Moyenne sans masque :"</span>, <span class="bu">round</span>(img.mean(), <span class="dv">2</span>))</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Moyenne avec masque :"</span>, <span class="bu">round</span>(img_masque.mean(), <span class="dv">2</span>))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Approche équivalente avec des NaN et les fonctions « nan » de NumPy</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>img_nan <span class="op">=</span> np.where(img <span class="op">==</span> <span class="dv">0</span>, np.nan, img)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Moyenne (nanmean)   :"</span>, <span class="bu">round</span>(np.nanmean(img_nan), <span class="dv">2</span>))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moyenne sans masque : 11.0
Moyenne avec masque : 16.5
Moyenne (nanmean)   : 16.5</code></pre>
</div>
</div>
</section>
<section id="calcul-dun-rapport-de-bandes" class="level3" data-number="2.3.5">
<h3 data-number="2.3.5" class="anchored" data-anchor-id="calcul-dun-rapport-de-bandes"><span class="header-section-number">2.3.5</span> Calcul d’un rapport de bandes</h3>
<p>Une opération très courante consiste à combiner deux bandes pixel par pixel. Par exemple, un rapport normalisé entre le proche-infrarouge et le rouge met en évidence la végétation (ce type d’indice spectral est approfondi au chapitre <a href="03-TransformationSpectrales.html" class="quarto-xref"><span>Chapitre 4</span></a>) :</p>
<div id="083e8c14" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rxr</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> rxr.open_rasterio(<span class="st">'RGBNIR_of_S2A.tif'</span>).astype(<span class="st">'float32'</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>rouge <span class="op">=</span> img.sel(band<span class="op">=</span><span class="dv">1</span>)     <span class="co"># bande 1 : rouge</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>pir   <span class="op">=</span> img.sel(band<span class="op">=</span><span class="dv">4</span>)     <span class="co"># bande 4 : proche-infrarouge</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Rapport normalisé (NIR - Rouge) / (NIR + Rouge)</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>rapport <span class="op">=</span> (pir <span class="op">-</span> rouge) <span class="op">/</span> (pir <span class="op">+</span> rouge)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Forme du rapport :"</span>, rapport.shape)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Valeurs min/max  :"</span>, <span class="bu">round</span>(<span class="bu">float</span>(rapport.<span class="bu">min</span>()), <span class="dv">2</span>), <span class="bu">round</span>(<span class="bu">float</span>(rapport.<span class="bu">max</span>()), <span class="dv">2</span>))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Forme du rapport : (1926, 2074)
Valeurs min/max  : -0.42 0.93</code></pre>
</div>
</div>
</section>
<section id="exportation-dune-image" class="level3" data-number="2.3.6">
<h3 data-number="2.3.6" class="anchored" data-anchor-id="exportation-dune-image"><span class="header-section-number">2.3.6</span> Exportation d’une image</h3>
<p>Une image chargée avec <code>rioxarray</code> peut être réécrite sur le disque au format GeoTIFF avec <code>rio.to_raster</code>, en conservant sa géoréférence :</p>
<div id="bf511d7e" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rxr</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> rxr.open_rasterio(<span class="st">'RGBNIR_of_S2A.tif'</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># On ne conserve que les trois premières bandes (rouge, vert, bleu)</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>img_rvb <span class="op">=</span> img.sel(band<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>])</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>img_rvb.rio.to_raster(<span class="st">'RGBNIR_rvb.tif'</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Image exportée :"</span>, <span class="bu">tuple</span>(img_rvb.sizes.values()))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Image exportée : (3, 1926, 2074)</code></pre>
</div>
</div>
</section>
<section id="changement-de-projection-cartographique" class="level3" data-number="2.3.7">
<h3 data-number="2.3.7" class="anchored" data-anchor-id="changement-de-projection-cartographique"><span class="header-section-number">2.3.7</span> Changement de projection cartographique</h3>
<p>Une image géoréférencée peut être reprojetée dans un autre système de coordonnées avec <code>rio.reproject</code>. <code>rioxarray</code> recalcule alors la grille de pixels et met à jour la géoréférence :</p>
<div id="b1584abe" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rxr</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> rxr.open_rasterio(<span class="st">'RGBNIR_of_S2A.tif'</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CRS d'origine :"</span>, img.rio.crs)              <span class="co"># EPSG:32618 (UTM)</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Reprojection en coordonnées géographiques (latitude/longitude)</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>img_wgs84 <span class="op">=</span> img.rio.reproject(<span class="st">"EPSG:4326"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Après reprojection :"</span>, img_wgs84.rio.crs)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Nouvelle forme :"</span>, <span class="bu">dict</span>(img_wgs84.sizes))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CRS d'origine : EPSG:32618</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Après reprojection : EPSG:4326
Nouvelle forme : {'band': 4, 'y': 1633, 'x': 2483}</code></pre>
</div>
</div>
<!--
### Recalage d'images et co-registration
-->
</section>
</section>
<section id="données-en-géoscience" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="données-en-géoscience"><span class="header-section-number">2.4</span> Données en géoscience</h2>
<p>Les données en géoscience contiennent beaucoup de métadonnées et peuvent être composées de différentes variables avec différentes unités, résolution, etc. Ces données sont aussi souvent étiquetées avec des dates sur certains axes, des coordonnées géographiques, des identifiants d’expériences, etc. Par conséquent, utiliser seulement des matrices est souvent incomplet <span class="citation" data-cites="xarray-2017">(<a href="references.html#ref-xarray-2017" role="doc-biblioref">Hoyer et Hamman 2017</a>)</span>.</p>
<p>Calibration, unités, données manquantes, données éparses.</p>
<section id="xarray" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="xarray"><span class="header-section-number">2.4.1</span> xarray</h3>
<p><a href="https://docs.xarray.dev/en/latest/getting-started-guide/why-xarray.html">Xarray</a> est une puissante bibliothèque Python qui améliore les matrices multidimensionnelles de type numpy en y ajoutant des étiquettes, des dimensions, des coordonnées et des attributs. Elle fournit deux structures de données principales : <code>DataArray</code> (un tableau étiqueté à n dimensions) et <code>Dataset</code> (une base de données de tableaux multidimensionnels en mémoire).</p>
<p>Les caractéristiques principales sont les suivantes:</p>
<ul>
<li><p>Opérations sur les dimensions nommées au lieu des numéros d’axe</p></li>
<li><p>Sélection et opérations basées sur les étiquettes</p></li>
<li><p>Diffusion automatique de tableaux basée sur les noms de dimensions</p></li>
<li><p>Alignement de type base de données avec des étiquettes de coordonnées</p></li>
<li><p>Suivi des métadonnées grâce à des dictionnaires Python</p></li>
</ul>
<section id="avantages" class="level4" data-number="2.4.1.1">
<h4 data-number="2.4.1.1" class="anchored" data-anchor-id="avantages"><span class="header-section-number">2.4.1.1</span> Avantages</h4>
<p>La bibliothèque réduit considérablement la complexité du code et améliore la lisibilité du code pour les applications de calcul scientifique dans divers domaines, notamment la physique, l’astronomie, les géosciences, la bio-informatique, l’ingénierie, la finance et l’apprentissage profond. Elle s’intègre de manière transparente avec NumPy et pandas tout en restant compatible avec l’écosystème Python au sens large.</p>
</section>
<section id="dataarray" class="level4" data-number="2.4.1.2">
<h4 data-number="2.4.1.2" class="anchored" data-anchor-id="dataarray"><span class="header-section-number">2.4.1.2</span> DataArray</h4>
<p>Un tableau multidimensionnel étiqueté avec des propriétés clées :</p>
<ul>
<li><p><code>valeurs</code> : Les données réelles du tableau</p></li>
<li><p><code>dims</code> : Dimensions nommées (par exemple, « x », « y », « z »)</p></li>
<li><p><code>coords</code> : Dictionnaire de tableaux étiquetant chaque point</p></li>
<li><p><code>attrs</code> : Stockage de métadonnées arbitraires</p></li>
<li><p><code>name</code> : Identifiant facultatif</p></li>
</ul>
</section>
<section id="dataset" class="level4" data-number="2.4.1.3">
<h4 data-number="2.4.1.3" class="anchored" data-anchor-id="dataset"><span class="header-section-number">2.4.1.3</span> Dataset</h4>
<p>Un conteneur de type dictionnaire de <code>DataArrays</code> avec des dimensions alignées, contenant :</p>
<ul>
<li><p><code>dims</code> : Dictionnaire de correspondance entre les noms des dimensions et les longueurs</p></li>
<li><p><code>data_vars</code> : Dictionnaire des variables du DataArray</p></li>
<li><p><code>coords</code> : Dictionnaire des variables de coordonnées</p></li>
<li><p><code>attrs</code> : Stockage des métadonnées</p></li>
</ul>
<p>Les principales différences sont les suivantes :</p>
<ul>
<li><p><code>DataArray</code> contient un seul tableau avec des étiquettes</p></li>
<li><p>Le <code>Dataset</code> contient plusieurs DataArrays alignés.</p></li>
</ul>
<p>Ces deux structures prennent en charge les opérations de type dictionnaire et les calculs de coordination tout en conservant les métadonnées.</p>
<div id="fig-xarray" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-xarray-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/xarray-dataset-diagram.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-xarray-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Organisation d’un Dataset dans xarray
</figcaption>
</figure>
</div>
</section>
<section id="exemple-avec-rioxarray" class="level4" data-number="2.4.1.4">
<h4 data-number="2.4.1.4" class="anchored" data-anchor-id="exemple-avec-rioxarray"><span class="header-section-number">2.4.1.4</span> Exemple avec rioxarray</h4>
<p><code>rioxarray</code> ouvre un GeoTIFF directement comme un <code>DataArray</code> étiqueté : ses dimensions (<code>band</code>, <code>y</code>, <code>x</code>), ses coordonnées et sa géoréférence sont accessibles via l’accesseur <code>.rio</code>. On peut alors sélectionner une bande par son étiquette plutôt que par un numéro d’axe :</p>
<div id="d23a0e58" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> rioxarray <span class="im">as</span> rxr</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> rxr.open_rasterio(<span class="st">'RGBNIR_of_S2A.tif'</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dimensions :"</span>, <span class="bu">dict</span>(img.sizes))</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Système de coordonnées :"</span>, img.rio.crs)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Résolution (m) :"</span>, img.rio.resolution())</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Sélection de la bande proche-infrarouge (bande 4) par son étiquette</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>pir <span class="op">=</span> img.sel(band<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Bande PIR — forme :"</span>, pir.shape, <span class="st">"| valeur maximale :"</span>, <span class="bu">int</span>(pir.<span class="bu">max</span>()))</span></code><button title="Copier vers le presse-papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensions : {'band': 4, 'y': 1926, 'x': 2074}
Système de coordonnées : EPSG:32618
Résolution (m) : (10.0, -10.0)
Bande PIR — forme : (1926, 2074) | valeur maximale : 15642</code></pre>
</div>
</div>
<!--
netcdf, xarray, GRIB.

Données météos, exemple avec SWOT.
-->
<!--
## Importation de données vectorielles

### Importation d'un fichier *shapefile*

### Importation d'une couche dans un *GeoPackage*

### Importation d'une couche dans une *geodatabase* d'ESRI

### Importation d'un fichier *shapefile*

## Manipulation de données vectorielles

### Requêtes attributaires 

## Exercices de révision
-->
</section>
</section>
</section>
<section id="quiz" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="quiz"><span class="header-section-number">2.5</span> Quiz</h2>
<div id="bd0c926b" class="cell" data-results="asis" data-execution_count="21">
<div class="cell-output cell-output-display" data-execution_count="17">
<div id="Chap01" class="card"><link type="text/javascript" src="libs/quizlib.1.0.1.min.js"><script>var Quiz=function(a,b){this.Classes=Object.freeze({QUESTION:"quizlib-question",QUESTION_TITLE:"quizlib-question-title",QUESTION_ANSWERS:"quizlib-question-answers",QUESTION_WARNING:"quizlib-question-warning",CORRECT:"quizlib-correct",INCORRECT:"quizlib-incorrect",TEMP:"quizlib-temp"}),this.unansweredQuestionText="Question sans réponse !",this.container=document.getElementById(a),this.questions=[],this.result=new QuizResult,this.answers=b;for(var c=0;c<this.container.children.length;c++)this.container.children[c].classList.contains(Quiz.Classes.QUESTION)&&this.questions.push(this.container.children[c]);if(this.answers.length!=this.questions.length)throw new Error("Number of answers does not match number of questions!")};Quiz.Classes=Object.freeze({QUESTION:"quizlib-question",QUESTION_TITLE:"quizlib-question-title",QUESTION_ANSWERS:"quizlib-question-answers",QUESTION_WARNING:"quizlib-question-warning",CORRECT:"quizlib-correct",INCORRECT:"quizlib-incorrect",TEMP:"quizlib-temp"}),Quiz.prototype.checkAnswers=function(a){void 0===a&&(a=!0);for(var b=[],c=[],d=0;d<this.questions.length;d++){var e=this.questions[d],f=this.answers[d],g=[];this.clearHighlights(e);for(var h,i=e.getElementsByClassName(Quiz.Classes.QUESTION_ANSWERS)[0].getElementsByTagName("input"),j=0;j<i.length;j++)h=i[j],"checkbox"===h.type||"radio"===h.type?h.checked&&g.push(h.value):""!==h.value&&g.push(h.value);1!=g.length||Array.isArray(f)?0===g.length&&b.push(e):g=g[0],c.push(Utils.compare(g,f))}if(0===b.length||!a)return this.result.setResults(c),!0;for(d=0;d<b.length;d++){var k=document.createElement("span");k.appendChild(document.createTextNode(this.unansweredQuestionText)),k.className=Quiz.Classes.QUESTION_WARNING,b[d].getElementsByClassName(Quiz.Classes.QUESTION_TITLE)[0].appendChild(k)}return!1},Quiz.prototype.clearHighlights=function(a){for(var b=a.getElementsByClassName(Quiz.Classes.QUESTION_WARNING);b.length>0;)b[0].parentNode.removeChild(b[0]);var c,d=[a.getElementsByClassName(Quiz.Classes.CORRECT),a.getElementsByClassName(this.Classes.INCORRECT)];for(i=0;i<d.length;i++)for(;d[i].length>0;)c=d[i][0],c.classList.remove(Quiz.Classes.CORRECT),c.classList.remove(Quiz.Classes.INCORRECT);for(var e=a.getElementsByClassName(Quiz.Classes.TEMP);e.length>0;)e[0].parentNode.removeChild(e[0])},Quiz.prototype.highlightResults=function(a){for(var b,c=0;c<this.questions.length;c++)b=this.questions[c],b.getElementsByClassName(Quiz.Classes.QUESTION_TITLE)[0].classList.add(this.result.results[c]?Quiz.Classes.CORRECT:Quiz.Classes.INCORRECT),void 0!==a&&a(this,b,c,this.result.results[c])};var QuizResult=function(){this.results=[],this.totalQuestions=0,this.score=0,this.scorePercent=0,this.scorePercentFormatted=0};QuizResult.prototype.setResults=function(a){this.results=a,this.totalQuestions=this.results.length,this.score=0;for(var b=0;b<this.results.length;b++)this.results[b]&&this.score++;this.scorePercent=this.score/this.totalQuestions,this.scorePercentFormatted=Math.floor(100*this.scorePercent)};var Utils=function(){};Utils.compare=function(a,b){if(a.length!=b.length)return!1;if(Array.isArray(a)&&Array.isArray(b)){for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0}return a===b};

function showResults(quiz) {
    // Check answers and continue if all questions have been answered
    if (quiz.checkAnswers()) {
        var quizScorePercent = quiz.result.scorePercentFormatted; // The unformatted percentage is a decimal in range 0 - 1
        var quizResultElement = document.getElementById('quiz-result');
        quizResultElement.style.display = 'block';
        document.getElementById('quiz-percent').innerHTML = quizScorePercent.toString();

        // Change background colour of results div according to score percent
        if (quizScorePercent > 75) quizResultElement.style.backgroundColor = '#4caf50';
        else if (quizScorePercent > 50) quizResultElement.style.backgroundColor = '#ffc107';
        else if (quizScorePercent > 25) quizResultElement.style.backgroundColor = '#ff9800';
        else if (quizScorePercent > 0) quizResultElement.style.backgroundColor = '#f44336';

        // Highlight questions according to whether they were correctly answered. The callback allows us to highlight/show the correct answer
        quiz.highlightResults(handleAnswers);
    }
}

/** Callback for Quiz.highlightResults. Highlights the correct answers of incorrectly answered questions
 * Parameters are: the quiz object, the question element, question number, correctly answered flag
 */
function handleAnswers(quiz, question, no, correct) {
    if (!correct) {
        var answers = question.getElementsByTagName('input');
        for (var i = 0; i < answers.length; i++) {
            if (answers[i].type === 'checkbox' || answers[i].type === 'radio'){
                // If the current input element is part of the correct answer, highlight it
                if (quiz.answers[no].indexOf(answers[i].value) > -1) {
                    answers[i].parentNode.classList.add(Quiz.Classes.CORRECT);
                }
            } else {
                // If the input is anything other than a checkbox or radio button, show the correct answer next to the element
                var correctAnswer = document.createElement('span');
                correctAnswer.classList.add(Quiz.Classes.CORRECT);
                correctAnswer.classList.add(Quiz.Classes.TEMP); // quiz.checkAnswers will automatically remove elements with the temp class
                correctAnswer.innerHTML = quiz.answers[no];
                correctAnswer.style.marginLeft = '10px';
                answers[i].parentNode.insertBefore(correctAnswer, answers[i].nextSibling);
            }
        }
    }
}

  var quizz_Chap01;
  window.onload = function() {
    quizz_Chap01 = new Quiz('Chap01', ['2','2',['1', '2', '3', '4'],'2','2','3','2',['1', '2', '3'],'2']);
  };</script><link rel="stylesheet" type="text/css" src="css/quizlib.min.css"><div class="card quizlib-question"><div class="quizlib-question-title">Quelle bibliothèque rassemble la plupart des formats matriciels en géomatique et permet de les lire et de les écrire ?</div><div>Relisez au besoin la section « Importation d'images ».</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>NumPy</label></td>
<td><input type="radio" name="q1" value="1"></td>
</tr>
<tr class="even">
<td><label>GDAL</label></td>
<td><input type="radio" name="q1" value="2"></td>
</tr>
<tr class="odd">
<td><label>Matplotlib</label></td>
<td><input type="radio" name="q1" value="3"></td>
</tr>
<tr class="even">
<td><label>Pandas</label></td>
<td><input type="radio" name="q1" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Les formats RVB grand public (JPEG, PNG) supportent généralement plus de trois bandes.</div><div>Relisez au besoin la section « Formats des images » : ces formats se limitent à trois bandes (RVB).</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>Vrai</label></td>
<td><input type="radio" name="q2" value="1"></td>
</tr>
<tr class="even">
<td><label>Faux</label></td>
<td><input type="radio" name="q2" value="2"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Parmi les caractéristiques suivantes d'une image, lesquelles distinguent les différents formats ?</div><div>Relisez au besoin la section « Importation d'images » : quatre caractéristiques principales.</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><label>La matrice des pixels</label></td>
<td><input type="checkbox" name="q3" value="1"></td>
</tr>
<tr class="even">
<td><label>La dynamique (le type de stockage des valeurs)</label></td>
<td><input type="checkbox" name="q3" value="2"></td>
</tr>
<tr class="odd">
<td><label>Le nombre de bandes</label></td>
<td><input type="checkbox" name="q3" value="3"></td>
</tr>
<tr class="even">
<td><label>La métadonnée (dont la géoréférence)</label></td>
<td><input type="checkbox" name="q3" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Quelle est la plage de valeurs d'un pixel de type `uint8` ?</div><div>Relisez au besoin le tableau des types de données NumPy (@tbl-numpytype).</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>de -128 à 127</label></td>
<td><input type="radio" name="q4" value="1"></td>
</tr>
<tr class="even">
<td><label>de 0 à 255</label></td>
<td><input type="radio" name="q4" value="2"></td>
</tr>
<tr class="odd">
<td><label>de 0 à 65535</label></td>
<td><input type="radio" name="q4" value="3"></td>
</tr>
<tr class="even">
<td><label>de 0 à 1</label></td>
<td><input type="radio" name="q4" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Dans quel ordre la fonction `cv2.imread` d'OpenCV renvoie-t-elle les canaux ?</div><div>Relisez au besoin la section « Lecture avec la librairie OpenCV ».</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>RGB (rouge, vert, bleu)</label></td>
<td><input type="radio" name="q5" value="1"></td>
</tr>
<tr class="even">
<td><label>BGR (bleu, vert, rouge)</label></td>
<td><input type="radio" name="q5" value="2"></td>
</tr>
<tr class="odd">
<td><label>En niveaux de gris</label></td>
<td><input type="radio" name="q5" value="3"></td>
</tr>
<tr class="even">
<td><label>CMJN</label></td>
<td><input type="radio" name="q5" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Pour une matrice NumPy `img`, quel attribut donne son type de stockage (par ex. `uint8`) ?</div><div>Relisez au besoin la section « Information de base ».</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>img.shape</label></td>
<td><input type="radio" name="q6" value="1"></td>
</tr>
<tr class="even">
<td><label>img.ndim</label></td>
<td><input type="radio" name="q6" value="2"></td>
</tr>
<tr class="odd">
<td><label>img.dtype</label></td>
<td><input type="radio" name="q6" value="3"></td>
</tr>
<tr class="even">
<td><label>img.size</label></td>
<td><input type="radio" name="q6" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Que sélectionne le découpage `matrice[:, 2, :]` ?</div><div>Relisez au besoin la section « Découpage et indexation de la matrice » : les indices commencent à 0.</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>La deuxième ligne</label></td>
<td><input type="radio" name="q7" value="1"></td>
</tr>
<tr class="even">
<td><label>La troisième colonne (indice 2), toutes bandes comprises</label></td>
<td><input type="radio" name="q7" value="2"></td>
</tr>
<tr class="odd">
<td><label>La bande numéro 2</label></td>
<td><input type="radio" name="q7" value="3"></td>
</tr>
<tr class="even">
<td><label>Un seul pixel</label></td>
<td><input type="radio" name="q7" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Quels avantages `xarray` / `rioxarray` apportent-ils par rapport à un simple tableau NumPy ?</div><div>Relisez au besoin la section « Données en géoscience ».</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><label>Des dimensions nommées (band, y, x)</label></td>
<td><input type="checkbox" name="q8" value="1"></td>
</tr>
<tr class="even">
<td><label>La sélection par étiquette avec `.sel`</label></td>
<td><input type="checkbox" name="q8" value="2"></td>
</tr>
<tr class="odd">
<td><label>L'accès à la géoréférence via l'accesseur `.rio`</label></td>
<td><input type="checkbox" name="q8" value="3"></td>
</tr>
<tr class="even">
<td><label>L'augmentation automatique de la résolution spatiale</label></td>
<td><input type="checkbox" name="q8" value="4"></td>
</tr>
</tbody>
</table>
</div></div><div class="card quizlib-question"><div class="quizlib-question-title">Quel format est un GeoTIFF optimisé pour un accès partiel via HTTP (infonuagique) ?</div><div>Relisez au besoin la section « Le format COG ».</div><div class="quizlib-question-answers">
<table class="table table-sm table-striped small caption-top" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td><label>JPEG</label></td>
<td><input type="radio" name="q9" value="1"></td>
</tr>
<tr class="even">
<td><label>COG (Cloud Optimized GeoTIFF)</label></td>
<td><input type="radio" name="q9" value="2"></td>
</tr>
<tr class="odd">
<td><label>PNG</label></td>
<td><input type="radio" name="q9" value="3"></td>
</tr>
<tr class="even">
<td><label>HDF5</label></td>
<td><input type="radio" name="q9" value="4"></td>
</tr>
</tbody>
</table>
</div></div><button type="button" onclick="showResults(quizz_Chap01);" id="buttonID">Vérifier votre résultat</button><div id="quiz-result" class="card"><span id="quiz-percent"></span></div></div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-NumpyNature" class="csl-entry" role="listitem">
Harris, Millman, C. R. 2020. <span>«&nbsp;Array programming with NumPy.&nbsp;»</span> <em><span>Nature</span></em>: 357‑362. <a href="https://doi.org/10.1038/s41586-020-2649-2">https://doi.org/10.1038/s41586-020-2649-2</a>.
</div>
<div id="ref-xarray-2017" class="csl-entry" role="listitem">
Hoyer, S. et J. Hamman. 2017. <span>«&nbsp;xarray: N-D labeled Arrays and Datasets in Python.&nbsp;»</span> <em><span>Journal of Open Research Software</span></em> 5 (1): 10. <a href="https://doi.org/10.5334/jors.148">https://doi.org/10.5334/jors.148</a>.
</div>
<div id="ref-OGCGeoTIFF" class="csl-entry" role="listitem">
OGC. 2019. <span>«&nbsp;<span>OGC GeoTIFF Standard</span>.&nbsp;»</span> <a href="https://docs.ogc.org/is/19-008r4/19-008r4.html/" class="uri">https://docs.ogc.org/is/19-008r4/19-008r4.html/</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/serie-python-tele\.github\.io\/TraitementImagesPythonVol1\/index\.html");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./00-PriseEnMainPython.html" class="pagination-link" aria-label="Introduction au langage Python">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction au langage Python</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02-RehaussementVisualisationImages.html" class="pagination-link" aria-label="Réhaussement et visualisation d'images">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Réhaussement et visualisation d’images</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Traitement d’images satellites avec Python.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sfoucher/TraitementImagesPythonVol1/issues" class="toc-action"><i class="bi bi-github"></i>Signaler un problème ou<br>formuler une suggestion</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Ce livre a été réalisé avec <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>